#!/bin/sh
sourceBranch=$1
destBranch=$2
echo $1 $2
if [ -z "$destBranch" ]; then
    destBranch=$(git branch --show-current)
fi

if [ "$destBranch" == "master" ]; then
    echo "Nao eh permitido fazer rebase na master"
    exit 1
else
    exit 0
fi
